### ISSUE TITLE
File upload error

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/bridge-gui#82]
error when trying to upload a +1GB .zip file:

[Sat Aug 13 2016 18:32:22 GMT+0200 (W. Europe Daylight Time)] [info]   Adding shard metadata for 076c4ebc6c4d3f25bb4f52e016773220c47f0521 to frame
[Sat Aug 13 2016 18:32:28 GMT+0200 (W. Europe Daylight Time)] [info]   Shard transfer completed! 281 remaining...
[Sat Aug 13 2016 18:32:28 GMT+0200 (W. Europe Daylight Time)] [info]   Trying to upload shard C:\Users\Meije\AppData\Local\Temp\5e4d7de76031 index 26
[Sat Aug 13 2016 18:32:33 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to upload shard...
[Sat Aug 13 2016 18:32:34 GMT+0200 (W. Europe Daylight Time)] [warn]   Error occured. Triggering cleanup...
[Sat Aug 13 2016 18:32:34 GMT+0200 (W. Europe Daylight Time)] [info]   Cleaning up...
fs.js:886
 return binding.rmdir(pathModule._makeLong(path));
                ^

Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\Meije\AppData\Local\Temp\storj-395083FFRGEtze1av'
   at Error (native)
   at Object.fs.rmdirSync (fs.js:886:18)
   at _rmdirRecursiveSync (C:\Users\Meije\AppData\Roaming\npm\node_modules\storj\node_modules\tmp\lib\tmp.js:285:10)
   at _cleanupCallback (C:\Users\Meije\AppData\Roaming\npm\node_modules\storj\node_modules\tmp\lib\tmp.js:409:5)
   at cleanup (C:\Users\Meije\AppData\Roaming\npm\node_modules\storj\bin\storj.js:477:11)
   at UploadState.callback (C:\Users\Meije\AppData\Roaming\npm\node_modules\storj\bin\storj.js:506:23)
   at C:\Users\Meije\AppData\Roaming\npm\node_modules\storj\lib\bridgeclient.js:461:22
   at C:\Users\Meije\AppData\Roaming\npm\node_modules\storj\lib\bridgeclient.js:310:16
   at Request._callback (C:\Users\Meije\AppData\Roaming\npm\node_modules\storj\lib\bridgeclient.js:826:14)
   at Request.self.callback (C:\Users\Meije\AppData\Roaming\npm\node_modules\storj\node_modules\request\request.js:187:22)
   at emitTwo (events.js:106:13)
   at Request.emit (events.js:191:7)
   at Request.<anonymous> (C:\Users\Meije\AppData\Roaming\npm\node_modules\storj\node_modules\request\request.js:1044:10)
   at emitOne (events.js:96:13)
   at Request.emit (events.js:188:7)
   at IncomingMessage.<anonymous> (C:\Users\Meije\AppData\Roaming\npm\node_modules\storj\node_modules\request\request.js:965:12)

![2016-08-13 1](https://cloud.githubusercontent.com/assets/11735738/17645845/3db98cea-61b1-11e6-9722-027777b05297.png)

**Comment by super3** [comment]
Uploads are not possible through bridge gui. This issue belongs in:
https://github.com/Storj/core
